name: drought
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - tensorflow==2.15.0
    - numpy==1.26.4
    - pandas==2.1.3
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - plotly
    - joblib==1.3.2
    - ipykernel
    - kaleido==0.2.1
    - nbformat
    - python-pptx
    - scikeras